version: '3.8'

services:
  postgis:
    image: postgis/postgis:16-3.4-alpine
    container_name: backend-database
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - backend-database_data:/var/lib/postgresql/data
    command: ["postgres", "-c", "timezone=Asia/Jakarta"]
    networks:
      - internal-network

volumes:
  backend-database_data:

networks:
  internal-network:
    external: true
